version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - jglick
  ignore:
  - dependency-name: com.google.guava:guava
  - dependency-name: com.google.inject.extensions:guice-assistedinject
